package com.kujtimhoxha.gradle.test;

/**
 * MyTest.
 *
 * @author Kujtim Hoxha (kujtimii.h@gmail.com)
 * @version $Id$
 * @since 0.1
 */
public class MyTest {
    /**
     *[todo] $ This is an autogenerated issue [issue=#1] $
     * #/
     * # My Issue
     * This issue is posted because this project uses [todo-issue-plugin](https://github.com/kujtimiihoxha/todo-issue)
     * #/
     * ~kujtimiihoxha~
     * %bug,dev,testissue%
     */
    private static final String myString="Testing todo-issue";

    public static void myMethod(){
        /**
         * [todo] $ Testing If Find Runs On Build [issue=#3] $
         * #/
         * This issue is a test of todo-issue gradle integration
         * #/
         */
        System.out.println("MyTest.myString = " + MyTest.myString);
    }
}
